In [35]:
from ultralytics import RTDETR
from ultralytics import RTDETR
import torch
from pathlib import Path
import pandas as pd

In [12]:
model = RTDETR("rtdetr-l.pt")
print("Loaded successfully")

Loaded successfully

In [13]:
print("Torch:", torch.__version__)

print("CUDA:", torch.cuda.is_available())

print("GPU:", torch.cuda.get_device_name(0))

Torch: 2.0.1+cu118
CUDA: True
GPU: NVIDIA H100 NVL

In [15]:
DATA_YAML = "/data/UG/Kiranmoy/datasets/MHCD2022_YOLO/data.yaml"

PROJECT_NAME = "MHCD_Benchmarks"
RUN_NAME = "RTDETR_L_Baseline"

In [ ]:
results = model.train(
    data=DATA_YAML,
    epochs=100,
    imgsz=640,
    batch=32,
    device=0,
    workers=8,
    seed=42,

    project="runs/detect/MHCD_Benchmarks",
    name="RTDETR_L_Baseline",

    pretrained=True,
    patience=20,
    verbose=True
)

Ultralytics 8.4.60 🚀 Python-3.10.20 torch-2.0.1+cu118 CUDA:0 (NVIDIA H100 NVL, 95235MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/data/UG/Kiranmoy/datasets/MHCD2022_YOLO/data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=100, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=rtdetr-l.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=RTDETR_L_Baseline, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=20, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=runs/detect/MHCD_Benchmarks, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/data/UG/Kiranmoy/Repo_Destination/High-Level-Military-Camouflage-Detection/runs/detect/runs/detect/MHCD_Benchmarks/RTDETR_L_Baseline, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=5
WARNING ⚠️ no model scale passed. Assuming scale='l'.

                   from  n    params  module                                       arguments
  0                  -1  1     25248  ultralytics.nn.modules.block.HGStem          [3, 32, 48]
  1                  -1  6    155072  ultralytics.nn.modules.block.HGBlock         [48, 48, 128, 3, 6]
  2                  -1  1      1408  ultralytics.nn.modules.conv.DWConv           [128, 128, 3, 2, 1, False]
  3                  -1  6    839296  ultralytics.nn.modules.block.HGBlock         [128, 96, 512, 3, 6]
  4                  -1  1      5632  ultralytics.nn.modules.conv.DWConv           [512, 512, 3, 2, 1, False]
  5                  -1  6   1695360  ultralytics.nn.modules.block.HGBlock         [512, 192, 1024, 5, 6, True, False]
  6                  -1  6   2055808  ultralytics.nn.modules.block.HGBlock         [1024, 192, 1024, 5, 6, True, True]
  7                  -1  6   2055808  ultralytics.nn.modules.block.HGBlock         [1024, 192, 1024, 5, 6, True, True]
  8                  -1  1     11264  ultralytics.nn.modules.conv.DWConv           [1024, 1024, 3, 2, 1, False]
  9                  -1  6   6708480  ultralytics.nn.modules.block.HGBlock         [1024, 384, 2048, 5, 6, True, False]
 10                  -1  1    524800  ultralytics.nn.modules.conv.Conv             [2048, 256, 1, 1, None, 1, 1, False]
 11                  -1  1    789760  ultralytics.nn.modules.transformer.AIFI      [256, 1024, 8]
 12                  -1  1     66048  ultralytics.nn.modules.conv.Conv             [256, 256, 1, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14                   7  1    262656  ultralytics.nn.modules.conv.Conv             [1024, 256, 1, 1, None, 1, 1, False]
 15            [-2, -1]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 17                  -1  1     66048  ultralytics.nn.modules.conv.Conv             [256, 256, 1, 1]
 18                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 19                   3  1    131584  ultralytics.nn.modules.conv.Conv             [512, 256, 1, 1, None, 1, 1, False]
 20            [-2, -1]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 22                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 23            [-1, 17]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 24                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 25                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 26            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 27                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 28        [21, 24, 27]  1   7312127  ultralytics.nn.modules.head.RTDETRDecoder    [5, [256, 256, 256]]
rt-detr-l summary: 465 layers, 32,816,351 parameters, 32,816,351 gradients, 108.0 GFLOPs

Transferred 926/941 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 7.7±8.0 MB/s, size: 209.6 KB)
train: Scanning /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/labels/train.cache... 2400 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 2400/2400 95.9Mit/s 0.0s
train: /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/train/000094.jpg: corrupt JPEG restored and saved
train: /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/train/000260.jpg: corrupt JPEG restored and saved
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 975.3±578.2 MB/s, size: 153.2 KB)
val: Scanning /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/labels/val.cache... 480 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 480/480 29.6Mit/s 0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.001111, momentum=0.9) with parameter groups 143 weight(decay=0.0), 206 weight(decay=0.0005), 226 bias(decay=0.0)
Plotting labels to /data/UG/Kiranmoy/Repo_Destination/High-Level-Military-Camouflage-Detection/runs/detect/runs/detect/MHCD_Benchmarks/RTDETR_L_Baseline/labels.jpg...
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /data/UG/Kiranmoy/Repo_Destination/High-Level-Military-Camouflage-Detection/runs/detect/runs/detect/MHCD_Benchmarks/RTDETR_L_Baseline
Starting training for 100 epochs...

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      1/100        83G      1.599      18.47     0.7766         32       1280: 0% ──────────── 0/75  12.7s

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      1/100      83.2G     0.9783      4.584      0.395         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.1s/it 1:190.8sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 5.8it/s 1.4s0.2s
                   all        480        682      0.396       0.38      0.312      0.187

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      2/100        83G     0.5337      0.589     0.1772         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.2it/s 1:010.8sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 5.6it/s 1.4s0.2s
                   all        480        682      0.712      0.607       0.64      0.352

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      3/100      83.2G     0.4586      0.549     0.1519         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.2it/s 1:000.8sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.5it/s 1.2s0.2s
                   all        480        682      0.671      0.701      0.718      0.465

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      4/100      83.3G     0.4323     0.5033     0.1404         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 60.0s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.3it/s 1.1s0.2s
                   all        480        682      0.839      0.721      0.779      0.503

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      5/100        83G     0.4211     0.5059     0.1386         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.2it/s 1:000.8sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.3it/s 1.1s0.2s
                   all        480        682       0.67      0.714      0.735      0.457

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      6/100      83.2G     0.4175     0.5041      0.132         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.2it/s 1:000.8sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.3it/s 1.1s0.2s
                   all        480        682      0.767      0.714      0.776      0.498

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      7/100      83.3G     0.3938     0.4886     0.1231         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.9s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.4it/s 1.1s0.2s
                   all        480        682      0.829      0.753      0.837      0.603

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      8/100      83.1G      0.376     0.4619     0.1213         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.8s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.8it/s 1.2s0.2s
                   all        480        682      0.812      0.775      0.824      0.557

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      9/100      83.2G     0.3552     0.4543     0.1117         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.2it/s 1:000.8sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.3it/s 1.1s0.2s
                   all        480        682       0.88      0.801      0.876      0.583

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     10/100        83G     0.3377     0.4205     0.1044         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.9s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 5.9it/s 1.4s0.2s
                   all        480        682      0.933       0.87      0.935      0.657

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     11/100      83.4G      0.339     0.4393     0.1041         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 60.0s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.1it/s 1.1s0.2s
                   all        480        682      0.906      0.834      0.909      0.637

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     12/100      83.3G     0.3256     0.4132     0.1005         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.8s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.9it/s 1.2s0.2s
                   all        480        682      0.826      0.841      0.897       0.63

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     13/100      83.4G      0.322     0.4111    0.09534         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.7s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.8it/s 1.2s0.2s
                   all        480        682      0.862      0.902      0.938      0.677

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     14/100      83.3G     0.3109     0.4018     0.0944         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.2it/s 1:000.8sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.3it/s 1.1s0.2s
                   all        480        682      0.902      0.916      0.969      0.686

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     15/100        83G     0.2967     0.3818    0.08496         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.8s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.1it/s 1.1s0.2s
                   all        480        682      0.921      0.896      0.946      0.669

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     16/100      83.3G     0.3059     0.3905    0.09025         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.2it/s 1:000.8sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.6it/s 1.2s0.2s
                   all        480        682      0.908      0.944      0.955      0.661

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     17/100      83.2G      0.299     0.3885    0.08632         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.9s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.0it/s 1.1s0.2s
                   all        480        682       0.87       0.85      0.927      0.672

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     18/100        83G     0.2987     0.4019    0.09288         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.2it/s 1:010.8sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.2it/s 1.1s0.2s
                   all        480        682      0.889      0.869      0.902       0.63

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     19/100      83.3G     0.2845      0.373    0.08041         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.8s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.0it/s 1.1s0.2s
                   all        480        682      0.932      0.943      0.977      0.757

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     20/100      83.3G     0.2794     0.3644    0.08065         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.9s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.3it/s 1.1s0.2s
                   all        480        682      0.928      0.914      0.956      0.691

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     21/100      83.5G     0.2583     0.3459    0.07257         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 60.0s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.3it/s 1.1s0.2s
                   all        480        682      0.933      0.933      0.956      0.735

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     22/100      83.3G     0.2603     0.3494    0.07278         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.9s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 5.2it/s 1.5s0.2s
                   all        480        682      0.969       0.94      0.975      0.703

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     23/100      83.4G     0.2361     0.3207    0.06515         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.2it/s 1:000.8sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.3it/s 1.1s0.2s
                   all        480        682      0.986      0.973      0.993      0.712

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     24/100      83.3G     0.2428     0.3263    0.06907         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.9s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.3it/s 1.1s0.2s
                   all        480        682      0.962      0.901       0.96      0.645

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     25/100      83.3G     0.2466     0.3381    0.06907         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.7s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.2it/s 1.3s0.2s
                   all        480        682      0.948      0.889      0.948      0.693

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     26/100      83.1G     0.2514     0.3384    0.06942         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.9s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.2it/s 1.1s0.2s
                   all        480        682      0.966      0.957       0.99      0.747

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     27/100      83.3G      0.239     0.3336    0.06688         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.4s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.9it/s 1.2s0.2s
                   all        480        682      0.966      0.926       0.96      0.727

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     28/100      83.3G     0.2348     0.3224    0.06609         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.6s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.1it/s 1.1s0.2s
                   all        480        682      0.971      0.956       0.98       0.75

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     29/100      83.3G      0.222     0.3101    0.06132         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.2it/s 1:000.8sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.8it/s 1.2s0.2s
                   all        480        682      0.978      0.954      0.982      0.771

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     30/100      83.2G     0.2286     0.3109    0.06319         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.6s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.1it/s 1.3s0.2s
                   all        480        682      0.974      0.942       0.98        0.8

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     31/100      83.4G     0.2177     0.2996    0.06149         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.9s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.2it/s 1.1s0.2s
                   all        480        682      0.959      0.901      0.948      0.761

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     32/100      83.1G     0.2174     0.3033    0.06021         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.6s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.2it/s 1.1s0.2s
                   all        480        682      0.945      0.962      0.973       0.73

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     33/100      83.4G     0.2233     0.3162     0.0638         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.8s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.1it/s 1.1s0.2s
                   all        480        682      0.958      0.887       0.97      0.753

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     34/100      83.2G     0.2184     0.3072      0.058         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.9s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.1it/s 1.1s0.2s
                   all        480        682      0.944      0.958      0.979      0.793

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     35/100      83.4G     0.2104     0.2976    0.05873         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.8s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.1it/s 1.1s0.2s
                   all        480        682      0.979      0.933      0.977      0.784

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     36/100      83.1G     0.2093     0.2938    0.05688         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.7s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.0it/s 1.3s0.2s
                   all        480        682      0.952      0.953      0.967      0.745

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     37/100      83.4G     0.2142     0.3033    0.06137         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.8s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.8it/s 1.2s0.2s
                   all        480        682      0.959      0.926      0.967      0.749

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     38/100      83.2G      0.205     0.2925    0.05498         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.6s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.2it/s 1.1s0.2s
                   all        480        682      0.983      0.954      0.984      0.734

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     39/100      83.4G     0.1994     0.2843    0.05202         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.8s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.2it/s 1.1s0.2s
                   all        480        682      0.968      0.968      0.986      0.793

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     40/100      83.2G     0.1936      0.278    0.05145         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.8s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.6it/s 1.2s0.2s
                   all        480        682      0.984      0.932      0.984      0.751

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     41/100      83.1G     0.1983     0.2864    0.05424         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.6s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.3it/s 1.1s0.2s
                   all        480        682      0.968      0.921      0.954      0.689

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     42/100      83.1G     0.1952     0.2856    0.05281         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.7s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.0it/s 1.2s0.2s
                   all        480        682       0.97       0.93      0.971      0.771

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     43/100      83.3G     0.1911     0.2806    0.05099         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.7s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.2it/s 1.1s0.2s
                   all        480        682      0.998      0.968      0.982      0.778

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     44/100      83.3G     0.1772     0.2591    0.04863         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.8s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.2it/s 1.1s0.2s
                   all        480        682      0.986      0.936      0.966      0.771

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     45/100      83.2G     0.1721     0.2603    0.04524         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.8s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.2it/s 1.1s0.2s
                   all        480        682      0.995      0.961      0.987      0.791

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     46/100      83.3G     0.1772     0.2642    0.04692         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.7s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.8it/s 1.2s0.2s
                   all        480        682      0.946      0.933      0.979      0.758

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     47/100      83.4G     0.1907     0.2831     0.0535         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.6s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.3it/s 1.1s0.2s
                   all        480        682      0.955      0.956      0.975      0.734

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     48/100      82.9G     0.2034     0.2998    0.05582         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.6s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.0it/s 1.1s0.2s
                   all        480        682      0.966      0.933      0.978      0.805

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     49/100      83.2G     0.1969       0.29    0.05351         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.7s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.2it/s 1.1s0.2s
                   all        480        682      0.959      0.947      0.966      0.769

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     50/100      83.1G     0.1798     0.2686    0.04975         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 60.0s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.2it/s 1.1s0.2s
                   all        480        682      0.988      0.916      0.986      0.775

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     51/100      83.4G     0.1819     0.2687     0.0505         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.5s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.1it/s 1.1s0.2s
                   all        480        682      0.963      0.937      0.973      0.773

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     52/100      83.2G     0.1839     0.2803    0.05099         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 60.0s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.2it/s 1.1s0.2s
                   all        480        682      0.966      0.913      0.969      0.776

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     53/100      83.3G     0.1805     0.2728    0.05163         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.7s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.9it/s 1.2s0.2s
                   all        480        682      0.971      0.927      0.957      0.771

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     54/100      83.1G     0.1745     0.2625    0.04671         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.6s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.0it/s 1.1s0.2s
                   all        480        682      0.983      0.908      0.974       0.78

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     55/100      83.4G     0.1651     0.2577    0.04272         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.9s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.2it/s 1.1s0.2s
                   all        480        682      0.968       0.92      0.971      0.779

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     56/100      83.1G     0.1728     0.2577    0.04522         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.7s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.2it/s 1.1s0.2s
                   all        480        682      0.987      0.948      0.974      0.782

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     57/100      83.2G     0.1679     0.2602    0.04522         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.5s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 5.9it/s 1.4s0.2s
                   all        480        682      0.975      0.955      0.985      0.766

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     58/100      83.3G     0.1659     0.2526    0.04556         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.9s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.2it/s 1.1s0.2s
                   all        480        682      0.977      0.931      0.966      0.761

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     59/100      83.1G     0.1695      0.257    0.04718         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.6s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.0it/s 1.1s0.2s
                   all        480        682      0.984      0.978      0.993      0.798

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     60/100      83.1G     0.1631     0.2452    0.04376         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.6s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.1it/s 1.1s0.2s
                   all        480        682      0.971      0.969       0.99       0.82

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     61/100      83.3G     0.1579     0.2406    0.04084         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.7s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.9it/s 1.2s0.2s
                   all        480        682      0.968      0.971      0.986      0.818

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     62/100      83.2G     0.1607     0.2442    0.04235         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.5s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 5.3it/s 1.5s0.2s
                   all        480        682      0.994      0.955      0.989      0.815

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     63/100      83.5G     0.1578     0.2376    0.04156         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.2it/s 1:000.8sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.0it/s 1.2s0.2s
                   all        480        682       0.99      0.984      0.993      0.811

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     64/100      83.2G     0.1575     0.2401    0.04329         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.6s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.2it/s 1.1s0.2s
                   all        480        682      0.962      0.989      0.993      0.811

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     65/100      83.3G     0.1595     0.2404    0.04176         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.8s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.1it/s 1.1s0.2s
                   all        480        682      0.983      0.984      0.993      0.823

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     66/100      83.3G     0.1563     0.2385    0.04078         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.7s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.2it/s 1.1s0.2s
                   all        480        682      0.976      0.967       0.99      0.805

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     67/100      83.1G     0.1562     0.2405    0.04402         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.7s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.1it/s 1.1s0.2s
                   all        480        682       0.96      0.952      0.984      0.792

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     68/100      83.3G     0.1605      0.247    0.04237         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.7s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.9it/s 1.2s0.2s
                   all        480        682      0.986      0.853      0.953      0.745

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     69/100      83.4G      0.157     0.2406    0.04289         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.5s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.2it/s 1.1s0.2s
                   all        480        682      0.959      0.891      0.965      0.814

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     70/100      83.3G     0.1486     0.2268    0.04041         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.6s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.9it/s 1.2s0.2s
                   all        480        682       0.98      0.952      0.979      0.786

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     71/100      83.3G     0.1486      0.225    0.03783         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.5s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.2it/s 1.3s0.2s
                   all        480        682       0.99      0.972       0.99      0.826

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     72/100      83.3G     0.1462     0.2264    0.03721         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.2it/s 1:000.8sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.6it/s 1.2s0.2s
                   all        480        682      0.967      0.951      0.985      0.819

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     73/100      83.3G     0.1432     0.2195     0.0362         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.6s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.0it/s 1.1s0.2s
                   all        480        682      0.982      0.979      0.989      0.833

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     74/100      83.2G     0.1402       0.22    0.03761         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.2it/s 1:000.8sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.1it/s 1.1s0.2s
                   all        480        682      0.993      0.963      0.987      0.823

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     75/100      83.4G     0.1369     0.2154    0.03503         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.2it/s 1:000.8sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.2it/s 1.1s0.2s
                   all        480        682      0.991      0.965      0.988      0.806

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     76/100      83.1G     0.1387     0.2132    0.03398         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.2it/s 1:010.8sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.2it/s 1.1s0.2s
                   all        480        682      0.989      0.975      0.991      0.799

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     77/100      83.4G     0.1357      0.211    0.03455         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.8s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.4it/s 1.3s0.2s
                   all        480        682      0.987      0.973      0.987      0.806

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     78/100      83.1G      0.128     0.2043    0.03286         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 60.0s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.8it/s 1.2s0.2s
                   all        480        682      0.983      0.971      0.991      0.813

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     79/100      83.5G     0.1303     0.2045    0.03399         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.9s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.1it/s 1.1s0.2s
                   all        480        682      0.979      0.966      0.975      0.803

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     80/100      83.3G     0.1305     0.2085    0.03284         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.9s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.1it/s 1.1s0.2s
                   all        480        682       0.97      0.959      0.983      0.822

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     81/100      83.2G       0.13     0.2055    0.03232         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.5s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.1it/s 1.1s0.2s
                   all        480        682      0.971      0.977      0.993      0.832

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     82/100      83.2G     0.1284     0.2044    0.03221         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.5s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.2it/s 1.1s0.2s
                   all        480        682      0.971      0.959      0.981      0.814

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     83/100      83.4G     0.1308     0.2064    0.03378         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.8s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.8it/s 1.2s0.2s
                   all        480        682      0.988       0.99      0.993      0.826

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     84/100      83.3G     0.1288     0.2011    0.03303         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 60.0s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.1it/s 1.1s0.2s
                   all        480        682      0.981      0.985      0.989      0.828

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     85/100      83.3G     0.1224     0.1981    0.03098         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.2it/s 1:000.8sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.1it/s 1.1s0.2s
                   all        480        682      0.995      0.979      0.989      0.809

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     86/100      83.1G     0.1229     0.1973    0.03079         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.5s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.0it/s 1.1s0.2s
                   all        480        682      0.986      0.976      0.981      0.808

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     87/100      83.2G     0.1239     0.1945    0.03135         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.6s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.1it/s 1.1s0.2s
                   all        480        682      0.986      0.961      0.984      0.828

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     88/100      83.3G     0.1239     0.2002    0.03041         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.8s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.1it/s 1.1s0.2s
                   all        480        682      0.982      0.978      0.991      0.825

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     89/100      83.4G     0.1206      0.195    0.03015         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.5s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.2it/s 1.1s0.2s
                   all        480        682      0.991      0.958      0.985      0.821

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     90/100      83.2G     0.1177       0.19    0.02954         32       1280: 100% ━━━━━━━━━━━━ 75/75 1.3it/s 59.5s0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.1it/s 1.1s0.2s
                   all        480        682      0.986       0.96      0.977      0.819
Closing dataloader mosaic

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     91/100      23.4G     0.2568     0.4484     0.2291         32        640: 0% ──────────── 0/75  1.0s

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     91/100      23.4G     0.1126      0.205    0.05265         32        640: 100% ━━━━━━━━━━━━ 75/75 3.1it/s 24.1s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.1it/s 1.1s0.2s
                   all        480        682      0.997      0.991      0.994      0.977

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     92/100      23.4G    0.09912      0.207    0.05434         32        640: 0% ──────────── 0/75  0.3s

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     92/100      23.4G     0.1045     0.1893    0.04644         32        640: 100% ━━━━━━━━━━━━ 75/75 3.4it/s 22.2s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.1it/s 1.1s0.2s
                   all        480        682      0.992      0.989      0.994      0.974

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     93/100      23.4G      0.112     0.1923    0.03881         32        640: 0% ──────────── 0/75  0.3s

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     93/100      23.4G     0.1054     0.1887    0.04932         32        640: 100% ━━━━━━━━━━━━ 75/75 3.4it/s 22.1s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.0it/s 1.1s0.2s
                   all        480        682       0.99      0.998      0.995      0.974

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     94/100      23.4G    0.09028      0.185    0.03821         32        640: 0% ──────────── 0/75  0.3s

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     94/100      23.4G    0.09991     0.1818    0.04315         32        640: 100% ━━━━━━━━━━━━ 75/75 3.3it/s 22.4s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.0it/s 1.1s0.2s
                   all        480        682       0.99          1      0.995      0.978

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     95/100      23.4G     0.1031     0.1805     0.0329         32        640: 0% ──────────── 0/75  0.4s

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     95/100      23.4G    0.09673     0.1721    0.04473         32        640: 100% ━━━━━━━━━━━━ 75/75 3.1it/s 24.4s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.9it/s 1.2s0.2s
                   all        480        682      0.996      0.998      0.995      0.977

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     96/100      23.4G    0.08932     0.1714    0.02714         32        640: 0% ──────────── 0/75  0.3s

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     96/100      23.4G    0.09491     0.1697    0.04068         32        640: 100% ━━━━━━━━━━━━ 75/75 3.4it/s 22.2s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.2it/s 1.3s0.2s
                   all        480        682      0.997      0.999      0.995      0.979

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     97/100      23.4G    0.07258     0.1454    0.03168         32        640: 0% ──────────── 0/75  0.3s

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     97/100      23.4G    0.09019     0.1657    0.03803         32        640: 100% ━━━━━━━━━━━━ 75/75 3.4it/s 22.4s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.7it/s 1.2s0.2s
                   all        480        682      0.997      0.998      0.995      0.979

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     98/100      23.4G    0.08277     0.1597    0.04035         32        640: 0% ──────────── 0/75  0.3s

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     98/100      23.4G    0.08642     0.1648    0.03672         32        640: 100% ━━━━━━━━━━━━ 75/75 3.3it/s 22.9s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.1it/s 1.1s0.2s
                   all        480        682       0.99      0.998      0.991      0.979

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     99/100      23.4G    0.09585     0.1713     0.0268         32        640: 0% ──────────── 0/75  0.3s

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     99/100      23.4G    0.08773     0.1599    0.03586         32        640: 100% ━━━━━━━━━━━━ 75/75 3.4it/s 22.4s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 7.1it/s 1.1s0.2s
                   all        480        682      0.997          1      0.995      0.982

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    100/100      23.4G    0.07445     0.1486    0.02491         32        640: 0% ──────────── 0/75  0.3s

/home/ug/.conda/envs/camouflage/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    100/100      23.4G    0.08573     0.1604    0.03736         32        640: 100% ━━━━━━━━━━━━ 75/75 2.9it/s 25.5s0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 6.2it/s 1.3s0.2s
                   all        480        682      0.998      0.991      0.995      0.983

100 epochs completed in 1.658 hours.
Optimizer stripped from /data/UG/Kiranmoy/Repo_Destination/High-Level-Military-Camouflage-Detection/runs/detect/runs/detect/MHCD_Benchmarks/RTDETR_L_Baseline/weights/last.pt, 66.2MB
Optimizer stripped from /data/UG/Kiranmoy/Repo_Destination/High-Level-Military-Camouflage-Detection/runs/detect/runs/detect/MHCD_Benchmarks/RTDETR_L_Baseline/weights/best.pt, 66.2MB

Validating /data/UG/Kiranmoy/Repo_Destination/High-Level-Military-Camouflage-Detection/runs/detect/runs/detect/MHCD_Benchmarks/RTDETR_L_Baseline/weights/best.pt...
Ultralytics 8.4.60 🚀 Python-3.10.20 torch-2.0.1+cu118 CUDA:0 (NVIDIA H100 NVL, 95235MiB)
rt-detr-l summary: 310 layers, 31,994,015 parameters, 0 gradients, 103.5 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 3.4it/s 2.4s0.2s
                   all        480        682      0.998      0.991      0.995      0.983
                person        417        524          1          1      0.995      0.968
      military vehicle         13         23      0.999      0.957      0.993      0.989
                  tank         35         64      0.998          1      0.995      0.984
             aeroplane         25         48      0.998          1      0.995      0.989
               warship         13         23      0.993          1      0.995      0.985
Speed: 0.7ms preprocess, 2.2ms inference, 0.0ms loss, 0.1ms postprocess per image
Results saved to /data/UG/Kiranmoy/Repo_Destination/High-Level-Military-Camouflage-Detection/runs/detect/runs/detect/MHCD_Benchmarks/RTDETR_L_Baseline

In [25]:
print(results.save_dir)

/data/UG/Kiranmoy/Repo_Destination/High-Level-Military-Camouflage-Detection/runs/detect/runs/detect/MHCD_Benchmarks/RTDETR_L_Baseline

In [26]:
best_model_path = Path(results.save_dir) / "weights" / "best.pt"

print(best_model_path)
print(best_model_path.exists())

/data/UG/Kiranmoy/Repo_Destination/High-Level-Military-Camouflage-Detection/runs/detect/runs/detect/MHCD_Benchmarks/RTDETR_L_Baseline/weights/best.pt
True

In [30]:
best_model = RTDETR(str(best_model_path))

metrics = best_model.val(
    data=DATA_YAML,
    split="test",
    device=0,
    workers=0
)

Ultralytics 8.4.60 🚀 Python-3.10.20 torch-2.0.1+cu118 CUDA:0 (NVIDIA H100 NVL, 95235MiB)
rt-detr-l summary: 310 layers, 31,994,015 parameters, 0 gradients, 103.5 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1911.7±448.5 MB/s, size: 126.8 KB)
val: Scanning /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/labels/test.cache... 600 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 600/600 64.5Mit/s 0.0s
val: /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000224.jpg: corrupt JPEG restored and saved
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 38/38 5.3it/s 7.2s0.2s
                   all        600        920      0.871      0.606      0.672       0.47
                person        531        718       0.97      0.798      0.878      0.594
      military vehicle         35         53      0.701      0.358      0.388      0.267
                  tank         49         89      0.865      0.607      0.682      0.503
             aeroplane         16         35      0.944      0.629       0.71      0.498
               warship         18         25      0.876       0.64      0.702      0.487
Speed: 0.2ms preprocess, 3.7ms inference, 0.0ms loss, 0.2ms postprocess per image
Results saved to /data/UG/Kiranmoy/Repo_Destination/High-Level-Military-Camouflage-Detection/runs/detect/val-2

In [31]:
print("AP50      :", metrics.box.map50)
print("AP75      :", metrics.box.map75)
print("AP50-95   :", metrics.box.map)

print("Precision :", metrics.box.mp)
print("Recall    :", metrics.box.mr)

f1 = (
    2 * metrics.box.mp * metrics.box.mr
    / (metrics.box.mp + metrics.box.mr + 1e-8)
)

print("F1        :", f1)

AP50      : 0.6719790979909728
AP75      : 0.4888868424505121
AP50-95   : 0.4698148103485957
Precision : 0.8712645500270024
Recall    : 0.6062982122086821
F1        : 0.7150236172272936

In [32]:
metrics.box.maps

array([    0.59385,     0.26708,     0.50322,     0.49835,     0.48658])

In [33]:
best_model.predict(
    source="/data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test",
    save=True,
    conf=0.25,
    project="runs/detect/MHCD_Benchmarks",
    name="RTDETR_TestPredictions"
)

image 1/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000013.jpg: 640x640 2 persons, 30.2ms
image 2/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000022.jpg: 640x640 2 persons, 30.2ms
image 3/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000025.jpg: 640x640 3 persons, 1 military vehicle, 1 tank, 30.1ms
image 4/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000028.jpg: 640x640 1 person, 29.6ms
image 5/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000033.jpg: 640x640 5 persons, 1 military vehicle, 1 tank, 29.4ms
image 6/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000034.jpg: 640x640 1 military vehicle, 31.2ms
image 7/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000038.jpg: 640x640 2 aeroplanes, 1 warship, 30.7ms
image 8/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000043.jpg: 640x640 1 person, 31.4ms
image 9/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000054.jpg: 640x640 1 military vehicle, 30.7ms
image 10/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000068.jpg: 640x640 1 warship, 32.0ms
image 11/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000075.jpg: 640x640 1 person, 33.0ms
image 12/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000077.jpg: 640x640 2 persons, 1 tank, 39.4ms
image 13/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000078.jpg: 640x640 1 person, 38.4ms
image 14/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000081.jpg: 640x640 2 persons, 34.0ms
image 15/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000084.jpg: 640x640 2 persons, 31.6ms
image 16/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000093.jpg: 640x640 1 warship, 36.2ms
image 17/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000096.jpg: 640x640 2 persons, 36.4ms
image 18/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000104.jpg: 640x640 1 person, 33.2ms
image 19/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000108.jpg: 640x640 2 warships, 33.3ms
image 20/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000122.jpg: 640x640 1 military vehicle, 34.5ms
image 21/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000125.jpg: 640x640 1 person, 32.3ms
image 22/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000126.jpg: 640x640 1 person, 1 military vehicle, 32.2ms
image 23/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000127.jpg: 640x640 1 person, 32.0ms
image 24/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000131.jpg: 640x640 1 person, 32.8ms
image 25/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000141.jpg: 640x640 2 persons, 31.6ms
image 26/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000144.jpg: 640x640 2 persons, 31.3ms
image 27/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000145.jpg: 640x640 1 person, 33.2ms
image 28/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000150.jpg: 640x640 1 person, 32.0ms
image 29/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000151.jpg: 640x640 1 person, 1 military vehicle, 31.1ms
image 30/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000155.jpg: 640x640 1 person, 31.1ms
image 31/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000157.jpg: 640x640 1 person, 32.2ms
image 32/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000162.jpg: 640x640 1 person, 32.6ms
image 33/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000166.jpg: 640x640 1 person, 31.3ms
image 34/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000167.jpg: 640x640 1 person, 1 tank, 30.7ms
image 35/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000180.jpg: 640x640 1 person, 32.1ms
image 36/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000183.jpg: 640x640 1 person, 30.1ms
image 37/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000191.jpg: 640x640 1 person, 33.1ms
image 38/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000194.jpg: 640x640 3 persons, 1 military vehicle, 1 tank, 35.0ms
image 39/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000197.jpg: 640x640 7 persons, 2 aeroplanes, 32.8ms
image 40/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000203.jpg: 640x640 2 tanks, 40.8ms
image 41/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000211.jpg: 640x640 5 persons, 1 military vehicle, 34.0ms
image 42/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000212.jpg: 640x640 1 person, 1 military vehicle, 1 tank, 32.9ms
image 43/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000224.jpg: 640x640 1 person, 34.5ms
image 44/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000227.jpg: 640x640 1 military vehicle, 1 tank, 33.9ms
image 45/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000228.jpg: 640x640 1 warship, 34.5ms
image 46/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000231.jpg: 640x640 1 person, 34.3ms
image 47/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000234.jpg: 640x640 8 persons, 1 tank, 34.0ms
image 48/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000240.jpg: 640x640 2 persons, 36.4ms
image 49/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000261.jpg: 640x640 2 military vehicles, 1 tank, 34.4ms
image 50/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000266.jpg: 640x640 2 persons, 1 tank, 35.2ms
image 51/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000268.jpg: 640x640 1 person, 35.6ms
image 52/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000272.jpg: 640x640 1 person, 36.4ms
image 53/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000280.jpg: 640x640 1 military vehicle, 35.5ms
image 54/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000288.jpg: 640x640 8 persons, 1 military vehicle, 35.3ms
image 55/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000294.jpg: 640x640 4 persons, 1 tank, 37.4ms
image 56/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000312.jpg: 640x640 2 military vehicles, 35.4ms
image 57/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000315.jpg: 640x640 2 persons, 1 tank, 34.9ms
image 58/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000323.jpg: 640x640 1 military vehicle, 1 aeroplane, 33.5ms
image 59/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000327.jpg: 640x640 1 person, 34.4ms
image 60/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000330.jpg: 640x640 7 persons, 2 military vehicles, 1 tank, 33.2ms
image 61/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000337.jpg: 640x640 1 tank, 34.4ms
image 62/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000338.jpg: 640x640 1 person, 28.7ms
image 63/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000342.jpg: 640x640 2 tanks, 28.9ms
image 64/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000344.jpg: 640x640 4 aeroplanes, 29.0ms
image 65/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000351.jpg: 640x640 1 person, 29.9ms
image 66/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000356.jpg: 640x640 2 persons, 1 military vehicle, 1 aeroplane, 29.3ms
image 67/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000360.jpg: 640x640 1 person, 1 tank, 29.7ms
image 68/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000368.jpg: 640x640 1 person, 30.4ms
image 69/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000369.jpg: 640x640 4 tanks, 31.3ms
image 70/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000370.jpg: 640x640 4 persons, 1 military vehicle, 31.5ms
image 71/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000375.jpg: 640x640 2 warships, 31.4ms
image 72/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000376.jpg: 640x640 1 warship, 31.8ms
image 73/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000383.jpg: 640x640 2 persons, 31.7ms
image 74/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000384.jpg: 640x640 3 persons, 3 tanks, 31.7ms
image 75/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000385.jpg: 640x640 1 person, 31.9ms
image 76/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000393.jpg: 640x640 3 tanks, 1 warship, 31.9ms
image 77/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000395.jpg: 640x640 1 person, 31.9ms
image 78/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000406.jpg: 640x640 1 person, 31.9ms
image 79/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000413.jpg: 640x640 1 person, 31.9ms
image 80/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000416.jpg: 640x640 1 person, 32.2ms
image 81/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000418.jpg: 640x640 1 person, 32.0ms
image 82/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000424.jpg: 640x640 1 person, 35.2ms
image 83/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000425.jpg: 640x640 5 persons, 32.1ms
image 84/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000435.jpg: 640x640 1 person, 31.9ms
image 85/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000437.jpg: 640x640 1 person, 31.9ms
image 86/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000452.jpg: 640x640 1 person, 32.1ms
image 87/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000455.jpg: 640x640 1 person, 32.2ms
image 88/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000457.jpg: 640x640 1 person, 1 military vehicle, 31.9ms
image 89/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000460.jpg: 640x640 1 person, 31.9ms
image 90/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000463.jpg: 640x640 1 person, 1 military vehicle, 31.8ms
image 91/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000467.jpg: 640x640 1 person, 31.8ms
image 92/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000485.jpg: 640x640 1 person, 31.9ms
image 93/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000497.jpg: 640x640 1 person, 1 tank, 32.1ms
image 94/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000502.jpg: 640x640 2 persons, 31.8ms
image 95/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000504.jpg: 640x640 4 persons, 32.3ms
image 96/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000506.jpg: 640x640 1 person, 31.7ms
image 97/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000511.jpg: 640x640 1 person, 31.7ms
image 98/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000523.jpg: 640x640 1 person, 32.0ms
image 99/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000524.jpg: 640x640 1 person, 32.1ms
image 100/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000526.jpg: 640x640 1 person, 23.5ms
image 101/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000528.jpg: 640x640 1 military vehicle, 19.9ms
image 102/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000529.jpg: 640x640 2 tanks, 18.9ms
image 103/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000534.jpg: 640x640 1 person, 18.4ms
image 104/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000536.jpg: 640x640 1 warship, 17.7ms
image 105/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000538.jpg: 640x640 1 person, 17.6ms
image 106/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000551.jpg: 640x640 1 person, 17.2ms
image 107/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000562.jpg: 640x640 4 persons, 16.9ms
image 108/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000566.jpg: 640x640 (no detections), 16.9ms
image 109/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000568.jpg: 640x640 2 persons, 16.9ms
image 110/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000577.jpg: 640x640 1 person, 16.8ms
image 111/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000583.jpg: 640x640 2 tanks, 16.8ms
image 112/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000585.jpg: 640x640 1 person, 16.7ms
image 113/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000586.jpg: 640x640 1 person, 16.8ms
image 114/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000588.jpg: 640x640 1 person, 1 tank, 16.8ms
image 115/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000591.jpg: 640x640 1 person, 16.7ms
image 116/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000593.jpg: 640x640 2 persons, 16.7ms
image 117/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000594.jpg: 640x640 1 person, 16.7ms
image 118/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000597.jpg: 640x640 1 person, 16.8ms
image 119/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000601.jpg: 640x640 1 person, 16.8ms
image 120/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000602.jpg: 640x640 1 person, 16.7ms
image 121/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000604.jpg: 640x640 1 person, 16.7ms
image 122/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000609.jpg: 640x640 1 person, 16.8ms
image 123/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000619.jpg: 640x640 1 person, 16.7ms
image 124/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000621.jpg: 640x640 1 person, 16.7ms
image 125/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000623.jpg: 640x640 1 person, 16.8ms
image 126/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000624.jpg: 640x640 1 person, 16.6ms
image 127/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000631.jpg: 640x640 1 person, 16.7ms
image 128/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000636.jpg: 640x640 1 person, 16.8ms
image 129/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000639.jpg: 640x640 5 persons, 4 aeroplanes, 16.8ms
image 130/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000643.jpg: 640x640 1 person, 16.8ms
image 131/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000646.jpg: 640x640 1 person, 18.9ms
image 132/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000649.jpg: 640x640 1 person, 16.8ms
image 133/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000658.jpg: 640x640 1 person, 16.7ms
image 134/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000659.jpg: 640x640 1 person, 16.7ms
image 135/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000665.jpg: 640x640 1 person, 16.8ms
image 136/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000669.jpg: 640x640 1 person, 16.8ms
image 137/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000679.jpg: 640x640 6 aeroplanes, 16.7ms
image 138/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000683.jpg: 640x640 2 tanks, 16.6ms
image 139/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000686.jpg: 640x640 1 person, 16.8ms
image 140/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000692.jpg: 640x640 1 person, 1 tank, 16.7ms
image 141/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000697.jpg: 640x640 1 tank, 16.7ms
image 142/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000701.jpg: 640x640 9 persons, 1 military vehicle, 16.8ms
image 143/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000707.jpg: 640x640 4 military vehicles, 1 aeroplane, 16.8ms
image 144/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000708.jpg: 640x640 1 tank, 16.8ms
image 145/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000712.jpg: 640x640 (no detections), 16.7ms
image 146/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000720.jpg: 640x640 (no detections), 16.8ms
image 147/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000724.jpg: 640x640 3 persons, 6 military vehicles, 1 tank, 16.7ms
image 148/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000725.jpg: 640x640 4 persons, 16.7ms
image 149/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000737.jpg: 640x640 2 persons, 16.7ms
image 150/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000738.jpg: 640x640 (no detections), 16.7ms
image 151/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000742.jpg: 640x640 1 person, 16.8ms
image 152/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000743.jpg: 640x640 2 persons, 16.8ms
image 153/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000744.jpg: 640x640 (no detections), 16.8ms
image 154/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000751.jpg: 640x640 2 tanks, 16.9ms
image 155/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000754.jpg: 640x640 3 tanks, 16.8ms
image 156/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000764.jpg: 640x640 1 person, 1 tank, 16.7ms
image 157/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000770.jpg: 640x640 1 person, 16.7ms
image 158/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000772.jpg: 640x640 1 person, 16.7ms
image 159/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000779.jpg: 640x640 1 tank, 1 aeroplane, 16.7ms
image 160/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000791.jpg: 640x640 2 persons, 17.0ms
image 161/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000798.jpg: 640x640 2 persons, 16.8ms
image 162/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000801.jpg: 640x640 4 persons, 1 military vehicle, 2 aeroplanes, 16.8ms
image 163/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000802.jpg: 640x640 1 aeroplane, 16.8ms
image 164/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000803.jpg: 640x640 1 tank, 17.2ms
image 165/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000814.jpg: 640x640 2 tanks, 16.8ms
image 166/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000815.jpg: 640x640 1 tank, 16.8ms
image 167/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000818.jpg: 640x640 (no detections), 16.6ms
image 168/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000819.jpg: 640x640 1 warship, 16.7ms
image 169/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000821.jpg: 640x640 1 tank, 16.8ms
image 170/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000823.jpg: 640x640 1 warship, 16.8ms
image 171/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000825.jpg: 640x640 3 persons, 1 tank, 16.7ms
image 172/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000826.jpg: 640x640 1 warship, 16.6ms
image 173/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000827.jpg: 640x640 2 persons, 16.7ms
image 174/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000828.jpg: 640x640 3 persons, 1 tank, 16.8ms
image 175/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000830.jpg: 640x640 1 military vehicle, 16.7ms
image 176/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000837.jpg: 640x640 1 person, 1 tank, 16.6ms
image 177/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000839.jpg: 640x640 1 military vehicle, 2 tanks, 16.8ms
image 178/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000850.jpg: 640x640 1 military vehicle, 1 tank, 16.7ms
image 179/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000854.jpg: 640x640 3 persons, 1 military vehicle, 1 tank, 1 aeroplane, 16.9ms
image 180/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000855.jpg: 640x640 2 persons, 16.7ms
image 181/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000865.jpg: 640x640 2 persons, 1 tank, 16.7ms
image 182/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000867.jpg: 640x640 2 persons, 17.0ms
image 183/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000877.jpg: 640x640 1 tank, 16.8ms
image 184/600 /data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000878.jpg: 640x640 2 persons, 16.7ms

[ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'person', 1: 'military vehicle', 2: 'tank', 3: 'aeroplane', 4: 'warship'}
 obb: None
 orig_img: array([[[246, 242, 241],
         [246, 242, 241],
         [246, 242, 241],
         ...,
         [231, 228, 224],
         [231, 228, 224],
         [233, 228, 224]],

        [[246, 242, 241],
         [246, 242, 241],
         [246, 242, 241],
         ...,
         [231, 228, 224],
         [231, 228, 224],
         [233, 228, 224]],

        [[246, 242, 241],
         [246, 242, 241],
         [246, 242, 241],
         ...,
         [231, 228, 224],
         [231, 228, 224],
         [233, 228, 224]],

        ...,

        [[ 33,  56,  75],
         [ 41,  64,  83],
         [ 45,  68,  87],
         ...,
         [ 17,  34,  45],
         [ 16,  32,  43],
         [ 16,  31,  42]],

        [[ 30,  53,  72],
         [ 38,  61,  80],
         [ 41,  64,  83],
         ...,
         [ 12,  29,  40],
         [ 12,  29,  40],
         [ 13,  27,  39]],

        [[ 26,  49,  68],
         [ 35,  59,  78],
         [ 39,  62,  81],
         ...,
         [ 10,  27,  38],
         [ 10,  27,  38],
         [ 11,  25,  36]]], dtype=uint8)
 orig_shape: (500, 781)
 path: '/data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000013.jpg'
 probs: None
 save_dir: '/data/UG/Kiranmoy/Repo_Destination/High-Level-Military-Camouflage-Detection/runs/detect/runs/detect/MHCD_Benchmarks/RTDETR_TestPredictions'
 semantic_mask: None
 speed: {'preprocess': 2.167545258998871, 'inference': 30.153140425682068, 'postprocess': 2.013593912124634},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'person', 1: 'military vehicle', 2: 'tank', 3: 'aeroplane', 4: 'warship'}
 obb: None
 orig_img: array([[[ 58, 104,  85],
         [ 69, 115,  96],
         [109, 154, 135],
         ...,
         [ 92, 145, 148],
         [ 63, 113, 119],
         [ 32,  82,  88]],

        [[ 75, 120, 101],
         [ 73, 118,  99],
         [ 70, 112,  94],
         ...,
         [199, 252, 255],
         [136, 186, 192],
         [119, 169, 175]],

        [[ 72, 110,  92],
         [ 80, 118, 100],
         [ 62, 100,  82],
         ...,
         [202, 253, 255],
         [173, 221, 225],
         [194, 242, 246]],

        ...,

        [[ 41,  75,  65],
         [ 37,  71,  61],
         [ 50,  78,  72],
         ...,
         [ 23,  65,  48],
         [ 35,  73,  55],
         [ 40,  79,  58]],

        [[ 21,  55,  45],
         [ 18,  52,  42],
         [ 33,  61,  55],
         ...,
         [ 13,  55,  38],
         [ 28,  66,  48],
         [ 35,  74,  53]],

        [[ 14,  48,  38],
         [  7,  41,  31],
         [ 19,  47,  41],
         ...,
         [  7,  49,  32],
         [ 22,  60,  42],
         [ 34,  73,  52]]], dtype=uint8)
 orig_shape: (1365, 2048)
 path: '/data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000022.jpg'
 probs: None
 save_dir: '/data/UG/Kiranmoy/Repo_Destination/High-Level-Military-Camouflage-Detection/runs/detect/runs/detect/MHCD_Benchmarks/RTDETR_TestPredictions'
 semantic_mask: None
 speed: {'preprocess': 2.9240772128105164, 'inference': 30.192852020263672, 'postprocess': 0.4329681396484375},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'person', 1: 'military vehicle', 2: 'tank', 3: 'aeroplane', 4: 'warship'}
 obb: None
 orig_img: array([[[ 26,  29,  26],
         [ 22,  26,  23],
         [ 34,  37,  35],
         ...,
         [196, 184, 179],
         [196, 184, 179],
         [196, 184, 179]],

        [[ 27,  30,  28],
         [ 28,  31,  29],
         [ 35,  38,  36],
         ...,
         [196, 184, 179],
         [196, 184, 179],
         [196, 184, 179]],

        [[ 28,  31,  29],
         [ 35,  38,  36],
         [ 38,  41,  38],
         ...,
         [196, 184, 179],
         [196, 184, 179],
         [196, 184, 179]],

        ...,

        [[190, 201, 211],
         [190, 201, 211],
         [190, 201, 211],
         ...,
         [108, 138, 143],
         [107, 136, 143],
         [107, 136, 143]],

        [[190, 201, 211],
         [190, 201, 211],
         [190, 201, 211],
         ...,
         [108, 138, 143],
         [107, 136, 143],
         [106, 135, 142]],

        [[190, 202, 209],
         [190, 202, 209],
         [190, 202, 209],
         ...,
         [108, 138, 143],
         [107, 136, 143],
         [106, 135, 142]]], dtype=uint8)
 orig_shape: (491, 600)
 path: '/data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000025.jpg'
 probs: None
 save_dir: '/data/UG/Kiranmoy/Repo_Destination/High-Level-Military-Camouflage-Detection/runs/detect/runs/detect/MHCD_Benchmarks/RTDETR_TestPredictions'
 semantic_mask: None
 speed: {'preprocess': 1.9926130771636963, 'inference': 30.112050473690033, 'postprocess': 0.4112720489501953},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'person', 1: 'military vehicle', 2: 'tank', 3: 'aeroplane', 4: 'warship'}
 obb: None
 orig_img: array([[[216, 205, 177],
         [222, 211, 183],
         [230, 219, 191],
         ...,
         [177, 161, 141],
         [119, 106,  85],
         [ 95,  84,  63]],

        [[227, 215, 188],
         [231, 220, 192],
         [236, 225, 197],
         ...,
         [126, 116,  97],
         [ 83,  79,  59],
         [ 90,  87,  67]],

        [[242, 231, 203],
         [243, 232, 204],
         [245, 234, 206],
         ...,
         [ 68,  75,  60],
         [ 69,  79,  64],
         [ 94, 106,  91]],

        ...,

        [[ 78,  86,  96],
         [ 38,  46,  56],
         [ 20,  28,  38],
         ...,
         [ 99, 130, 148],
         [ 86, 117, 135],
         [ 76, 106, 124]],

        [[ 39,  47,  57],
         [ 13,  21,  31],
         [ 13,  21,  31],
         ...,
         [140, 171, 187],
         [112, 143, 160],
         [ 89, 119, 137]],

        [[ 60,  68,  78],
         [ 27,  35,  45],
         [ 21,  29,  39],
         ...,
         [181, 212, 227],
         [162, 193, 210],
         [120, 151, 168]]], dtype=uint8)
 orig_shape: (413, 550)
 path: '/data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000028.jpg'
 probs: None
 save_dir: '/data/UG/Kiranmoy/Repo_Destination/High-Level-Military-Camouflage-Detection/runs/detect/runs/detect/MHCD_Benchmarks/RTDETR_TestPredictions'
 semantic_mask: None
 speed: {'preprocess': 1.8627345561981201, 'inference': 29.59592640399933, 'postprocess': 0.3940165042877197},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'person', 1: 'military vehicle', 2: 'tank', 3: 'aeroplane', 4: 'warship'}
 obb: None
 orig_img: array([[[208, 192, 175],
         [208, 192, 175],
         [208, 192, 175],
         ...,
         [210, 189, 167],
         [210, 189, 167],
         [210, 189, 167]],

        [[208, 192, 175],
         [208, 192, 175],
         [208, 192, 175],
         ...,
         [210, 189, 167],
         [211, 190, 168],
         [211, 190, 168]],

        [[208, 192, 175],
         [208, 192, 175],
         [208, 192, 175],
         ...,
         [210, 189, 168],
         [211, 190, 168],
         [211, 190, 168]],

        ...,

        [[108, 134, 151],
         [105, 131, 148],
         [103, 129, 146],
         ...,
         [ 94, 123, 138],
         [101, 129, 146],
         [100, 128, 145]],

        [[106, 132, 149],
         [107, 133, 150],
         [108, 134, 151],
         ...,
         [100, 128, 145],
         [108, 136, 153],
         [105, 133, 150]],

        [[107, 133, 150],
         [108, 134, 151],
         [109, 135, 152],
         ...,
         [110, 138, 155],
         [101, 129, 146],
         [ 97, 125, 142]]], dtype=uint8)
 orig_shape: (384, 594)
 path: '/data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000033.jpg'
 probs: None
 save_dir: '/data/UG/Kiranmoy/Repo_Destination/High-Level-Military-Camouflage-Detection/runs/detect/runs/detect/MHCD_Benchmarks/RTDETR_TestPredictions'
 semantic_mask: None
 speed: {'preprocess': 1.831240952014923, 'inference': 29.384680092334747, 'postprocess': 0.41122734546661377},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'person', 1: 'military vehicle', 2: 'tank', 3: 'aeroplane', 4: 'warship'}
 obb: None
 orig_img: array([[[101, 130, 119],
         [ 70,  99,  87],
         [ 73, 102,  91],
         ...,
         [133, 131, 124],
         [118, 113, 107],
         [145, 140, 134]],

        [[ 84, 113, 101],
         [ 70,  99,  87],
         [ 88, 117, 106],
         ...,
         [146, 144, 137],
         [174, 169, 163],
         [209, 204, 198]],

        [[ 85, 114, 102],
         [ 87, 116, 105],
         [115, 144, 133],
         ...,
         [175, 173, 166],
         [218, 213, 207],
         [253, 248, 242]],

        ...,

        [[254, 254, 254],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[254, 254, 254],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[254, 254, 254],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]]], dtype=uint8)
 orig_shape: (500, 750)
 path: '/data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000034.jpg'
 probs: None
 save_dir: '/data/UG/Kiranmoy/Repo_Destination/High-Level-Military-Camouflage-Detection/runs/detect/runs/detect/MHCD_Benchmarks/RTDETR_TestPredictions'
 semantic_mask: None
 speed: {'preprocess': 2.021223306655884, 'inference': 31.182125210762024, 'postprocess': 0.42185187339782715},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'person', 1: 'military vehicle', 2: 'tank', 3: 'aeroplane', 4: 'warship'}
 obb: None
 orig_img: array([[[106, 126, 159],
         [109, 130, 163],
         [114, 135, 168],
         ...,
         [ 98, 126, 151],
         [ 69,  97, 122],
         [ 83, 111, 136]],

        [[102, 124, 154],
         [106, 127, 158],
         [110, 132, 163],
         ...,
         [105, 133, 158],
         [ 98, 126, 151],
         [ 98, 126, 151]],

        [[ 98, 120, 148],
         [101, 123, 152],
         [106, 128, 156],
         ...,
         [110, 138, 163],
         [ 89, 117, 142],
         [ 67,  95, 120]],

        ...,

        [[135, 167, 186],
         [135, 167, 186],
         [135, 167, 186],
         ...,
         [ 92, 118, 141],
         [ 87, 114, 137],
         [ 83, 109, 132]],

        [[135, 167, 186],
         [135, 167, 186],
         [136, 168, 188],
         ...,
         [ 93, 119, 144],
         [ 90, 115, 141],
         [ 86, 112, 137]],

        [[135, 167, 186],
         [135, 167, 186],
         [136, 168, 188],
         ...,
         [ 93, 119, 144],
         [ 90, 115, 141],
         [ 86, 112, 137]]], dtype=uint8)
 orig_shape: (426, 640)
 path: '/data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000038.jpg'
 probs: None
 save_dir: '/data/UG/Kiranmoy/Repo_Destination/High-Level-Military-Camouflage-Detection/runs/detect/runs/detect/MHCD_Benchmarks/RTDETR_TestPredictions'
 semantic_mask: None
 speed: {'preprocess': 1.9330531358718872, 'inference': 30.71727603673935, 'postprocess': 0.405140221118927},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'person', 1: 'military vehicle', 2: 'tank', 3: 'aeroplane', 4: 'warship'}
 obb: None
 orig_img: array([[[ 13,  20,  19],
         [ 13,  20,  19],
         [ 14,  21,  20],
         ...,
         [ 93, 125, 144],
         [ 93, 125, 144],
         [ 93, 124, 146]],

        [[ 13,  20,  19],
         [ 13,  20,  19],
         [ 14,  21,  20],
         ...,
         [ 93, 125, 144],
         [ 93, 125, 144],
         [ 93, 124, 146]],

        [[ 13,  20,  19],
         [ 13,  20,  19],
         [ 14,  21,  20],
         ...,
         [ 93, 125, 144],
         [ 93, 125, 144],
         [ 93, 124, 146]],

        ...,

        [[ 73,  94, 127],
         [ 73,  94, 127],
         [ 73,  94, 127],
         ...,
         [103, 132, 168],
         [103, 132, 168],
         [105, 132, 168]],

        [[ 74,  95, 128],
         [ 74,  95, 128],
         [ 74,  95, 128],
         ...,
         [103, 132, 168],
         [103, 132, 168],
         [105, 132, 168]],

        [[ 74,  95, 128],
         [ 74,  95, 128],
         [ 74,  95, 128],
         ...,
         [103, 132, 168],
         [103, 132, 168],
         [105, 132, 168]]], dtype=uint8)
 orig_shape: (1600, 2405)
 path: '/data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000043.jpg'
 probs: None
 save_dir: '/data/UG/Kiranmoy/Repo_Destination/High-Level-Military-Camouflage-Detection/runs/detect/runs/detect/MHCD_Benchmarks/RTDETR_TestPredictions'
 semantic_mask: None
 speed: {'preprocess': 2.745978534221649, 'inference': 31.440086662769318, 'postprocess': 0.4483535885810852},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'person', 1: 'military vehicle', 2: 'tank', 3: 'aeroplane', 4: 'warship'}
 obb: None
 orig_img: array([[[235, 162, 115],
         [235, 162, 115],
         [235, 162, 115],
         ...,
         [204, 142, 102],
         [204, 142, 102],
         [204, 142, 102]],

        [[235, 162, 115],
         [235, 162, 115],
         [235, 162, 115],
         ...,
         [204, 142, 102],
         [204, 142, 102],
         [204, 142, 102]],

        [[235, 162, 115],
         [235, 162, 115],
         [235, 162, 115],
         ...,
         [204, 142, 102],
         [204, 142, 102],
         [204, 142, 102]],

        ...,

        [[ 67, 157, 133],
         [ 55, 145, 122],
         [ 53, 140, 117],
         ...,
         [110, 117, 130],
         [105, 105, 119],
         [ 90,  91, 102]],

        [[ 71, 161, 137],
         [ 66, 156, 132],
         [ 67, 154, 131],
         ...,
         [170, 178, 190],
         [153, 156, 169],
         [142, 145, 156]],

        [[ 66, 156, 132],
         [ 68, 158, 135],
         [ 71, 159, 136],
         ...,
         [182, 192, 204],
         [176, 181, 194],
         [182, 187, 198]]], dtype=uint8)
 orig_shape: (500, 667)
 path: '/data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000054.jpg'
 probs: None
 save_dir: '/data/UG/Kiranmoy/Repo_Destination/High-Level-Military-Camouflage-Detection/runs/detect/runs/detect/MHCD_Benchmarks/RTDETR_TestPredictions'
 semantic_mask: None
 speed: {'preprocess': 2.0472779870033264, 'inference': 30.739933252334595, 'postprocess': 0.4278793931007385},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'person', 1: 'military vehicle', 2: 'tank', 3: 'aeroplane', 4: 'warship'}
 obb: None
 orig_img: array([[[175, 119,  78],
         [175, 119,  78],
         [175, 119,  78],
         ...,
         [203, 147, 106],
         [203, 147, 106],
         [203, 147, 106]],

        [[175, 119,  78],
         [175, 119,  78],
         [175, 119,  78],
         ...,
         [203, 147, 106],
         [203, 147, 106],
         [203, 147, 106]],

        [[175, 119,  78],
         [175, 119,  78],
         [175, 119,  78],
         ...,
         [203, 147, 106],
         [203, 147, 106],
         [203, 147, 106]],

        ...,

        [[104,  79,  58],
         [102,  77,  56],
         [ 99,  74,  53],
         ...,
         [ 93,  63,  43],
         [ 97,  68,  48],
         [100,  70,  50]],

        [[109,  84,  63],
         [103,  78,  57],
         [ 97,  72,  51],
         ...,
         [110,  81,  60],
         [114,  84,  64],
         [117,  88,  67]],

        [[103,  78,  57],
         [100,  76,  55],
         [ 99,  74,  53],
         ...,
         [124,  94,  76],
         [124,  94,  76],
         [124,  94,  76]]], dtype=uint8)
 orig_shape: (333, 640)
 path: '/data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000068.jpg'
 probs: None
 save_dir: '/data/UG/Kiranmoy/Repo_Destination/High-Level-Military-Camouflage-Detection/runs/detect/runs/detect/MHCD_Benchmarks/RTDETR_TestPredictions'
 semantic_mask: None
 speed: {'preprocess': 1.8777698278427124, 'inference': 32.03616291284561, 'postprocess': 0.4299655556678772},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'person', 1: 'military vehicle', 2: 'tank', 3: 'aeroplane', 4: 'warship'}
 obb: None
 orig_img: array([[[ 51,  79,  79],
         [ 55,  83,  83],
         [ 60,  84,  84],
         ...,
         [ 71, 110, 112],
         [ 78, 116, 116],
         [ 82, 120, 120]],

        [[ 50,  78,  78],
         [ 53,  81,  81],
         [ 57,  81,  81],
         ...,
         [ 67, 106, 108],
         [ 73, 111, 111],
         [ 77, 115, 115]],

        [[ 48,  76,  76],
         [ 51,  79,  79],
         [ 53,  77,  77],
         ...,
         [ 62, 101, 103],
         [ 68, 106, 108],
         [ 72, 110, 112]],

        ...,

        [[ 60,  74,  92],
         [ 52,  66,  84],
         [ 51,  65,  83],
         ...,
         [ 73,  74,  88],
         [ 34,  34,  50],
         [ 58,  58,  74]],

        [[ 88, 103, 119],
         [104, 119, 135],
         [116, 131, 147],
         ...,
         [ 84,  85,  99],
         [ 49,  49,  65],
         [ 59,  59,  75]],

        [[ 45,  60,  76],
         [ 62,  77,  93],
         [ 80,  95, 111],
         ...,
         [100, 101, 115],
         [ 87,  87, 103],
         [ 84,  84, 100]]], dtype=uint8)
 orig_shape: (398, 640)
 path: '/data/UG/Kiranmoy/datasets/MHCD2022_YOLO/images/test/000075.jpg'
 probs: None
 save_dir: '/data/UG/Kiranmoy/Repo_Destination/High-Level-Military-Camouflage-Detection/runs/detect/runs/detect/MHCD_Benchmarks/RTDETR_TestPredictions'
 semantic_mask: None
 speed: {'preprocess': 1.951955258846283, 'inference': 32.98357129096985, 'postprocess': 0.5054771900177002},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'person', 1: 'military vehicle', 2: 'tank', 3: 'aeroplane', 4: 'warship'}
 obb: None
 orig_img: array([[[ 18,  54,  62],
         [ 23,  59,  67],
         [ 29,  65,  72],
         ...,
         [202, 207, 206],
         [204, 209, 208],
         [210, 215, 214]],

        [[ 18,  54,  62],
         [ 23,  59,  67],
         [ 29,  65,  72],
         ...,
         [194, 199, 198],
         [196, 201, 200],
         [202, 207, 206]],

        [[ 19,  55,  63],
         [ 23,  59,  67],
         [ 29,  65,  72],
         ...,
         [190, 196, 193],
         [193, 198, 195],
         [199, 204, 201]],

        ...,

        [[181, 184, 181],
         [170, 174, 171],
         [168, 173, 172],
         ...,
         [115, 130, 132],
         [115, 130, 132],
         [121, 136, 138]],

        [[203, 207, 202],
         [185, 189, 186],
         [173, 178, 177],
         ...,
         [109, 125, 127],
         [115, 130, 132],
         [124, 140, 142]],

        [[212, 216, 211],
         [190, 193, 191],
         [169, 174, 173],
         ...,
         [112, 127, 129],
         [116, 132, 134],
         [123, 139, 141]]], dtype=uint8)

In [40]:
detector_benchmark = pd.DataFrame([
    {
        "Model": "YOLO11-s",
        "AP50": 0.639971,
        "AP75": 0.430297,
        "AP50-95": 0.406923,
        "Precision": 0.803039,
        "Recall": 0.581678,
        "F1": 0.674665
    },
    {
        "Model": "RTDETR-L",
        "AP50": 0.671979,
        "AP75": 0.488887,
        "AP50-95": 0.469815,
        "Precision": 0.871265,
        "Recall": 0.606298,
        "F1": 0.715024
    }
])

detector_benchmark.to_csv(
    "Detector_Benchmark.csv",
    index=False
)

detector_benchmark

      Model      AP50      AP75   AP50-95  Precision    Recall        F1
0  YOLO11-s  0.639971  0.430297  0.406923   0.803039  0.581678  0.674665
1  RTDETR-L  0.671979  0.488887  0.469815   0.871265  0.606298  0.715024

In [42]:
classwise_benchmark = pd.DataFrame([
    {
        "Model": "YOLO11-s",
        "Person": 0.53718,
        "Military Vehicle": 0.23058,
        "Tank": 0.44705,
        "Aeroplane": 0.37124,
        "Warship": 0.44857
    },
    {
        "Model": "RTDETR-L",
        "Person": 0.59385,
        "Military Vehicle": 0.26708,
        "Tank": 0.50322,
        "Aeroplane": 0.49835,
        "Warship": 0.48658
    }
])

classwise_benchmark.to_csv(
    "Classwise_Benchmark.csv",
    index=False
)

classwise_benchmark

      Model   Person  Military Vehicle     Tank  Aeroplane  Warship
0  YOLO11-s  0.53718           0.23058  0.44705    0.37124  0.44857
1  RTDETR-L  0.59385           0.26708  0.50322    0.49835  0.48658